version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/trakto
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - compose-network

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - compose-network

  rabbitmq:
    image: rabbitmq:3.12-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - compose-network

volumes:
  mongo_data:
networks:
  compose-network:
    driver: bridge